version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:db/development.sqlite3
    volumes:
      - ./db:/rails/db
volumes:
  pgdata:
